---
monitor:
  system:
    enabled: True
    updater: True
  docker:
    enabled: True
  kube:
    enabled: True
    name: "julina"

elastic:
  url: "https://elasticsearch:9200"
  user: ""
  pass: ""
